/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TemplateClassic {
        "tokken": string;
    }
    interface TemplateInsta {
        "headerTitle": string;
        "tokken": string;
    }
}
declare global {
    interface HTMLTemplateClassicElement extends Components.TemplateClassic, HTMLStencilElement {
    }
    var HTMLTemplateClassicElement: {
        prototype: HTMLTemplateClassicElement;
        new (): HTMLTemplateClassicElement;
    };
    interface HTMLTemplateInstaElement extends Components.TemplateInsta, HTMLStencilElement {
    }
    var HTMLTemplateInstaElement: {
        prototype: HTMLTemplateInstaElement;
        new (): HTMLTemplateInstaElement;
    };
    interface HTMLElementTagNameMap {
        "template-classic": HTMLTemplateClassicElement;
        "template-insta": HTMLTemplateInstaElement;
    }
}
declare namespace LocalJSX {
    interface TemplateClassic {
        "tokken"?: string;
    }
    interface TemplateInsta {
        "headerTitle"?: string;
        "tokken"?: string;
    }
    interface IntrinsicElements {
        "template-classic": TemplateClassic;
        "template-insta": TemplateInsta;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "template-classic": LocalJSX.TemplateClassic & JSXBase.HTMLAttributes<HTMLTemplateClassicElement>;
            "template-insta": LocalJSX.TemplateInsta & JSXBase.HTMLAttributes<HTMLTemplateInstaElement>;
        }
    }
}
